#Auto-incremented patch version
#Thu Sep 24 02:57:19 UTC 2026
app.version.major=9
app.build.date=2026-09-24
app.version.patch=23
app.release.notes.url=https\://github.com/risa-labs-inc/BossConsole-Releases/releases/tag/v8.9.0
app.version.minor=5
app.release.channel=stable
app.version=9.5.23
app.build.number=1
app.prerelease.suffix=
