#Auto-incremented patch version
#Thu Jul 23 23:55:20 UTC 2026
app.version.major=9
app.build.date=2026-07-23
app.version.patch=57
app.release.notes.url=https\://github.com/risa-labs-inc/BossConsole-Releases/releases/tag/v8.9.0
app.bundle.version=9.2.57
app.version.minor=2
app.release.channel=stable
app.version=9.2.57
app.build.number=1
app.prerelease.suffix=
