#Auto-incremented patch version
#Tue Jul 21 04:52:12 UTC 2026
app.version.major=9
app.build.date=2026-07-21
app.version.patch=53
app.release.notes.url=https\://github.com/risa-labs-inc/BossConsole-Releases/releases/tag/v8.9.0
app.bundle.version=9.2.53
app.version.minor=2
app.release.channel=stable
app.version=9.2.53
app.build.number=1
app.prerelease.suffix=
