package ai.rever.boss.plugin.logging

/**
 * Makes text safe to put inside ONE kernel log record.
 *
 * The kernel log is line-oriented: the in-app log panel, the console capture, and any tail or grep
 * treat a newline as the end of a record. Unescaped line breaks in text from outside the logger
 * (such as a child process's surface id, state keys, URLs, or error bodies) let an unprivileged caller
 * split a record and forge subsequent log lines that appear to be generated by the kernel (CWE-117).
 * Terminal escapes and bidi overrides change what a line appears to say without changing its bytes.
 *
 * Line breaks become `\n` / `\r`, backslashes become `\\`, and the rest become UTF-16 `\uXXXX`
 * escapes. Nothing is dropped, so the original is recoverable from the escaped form. A tab is kept
 * as ordinary layout inside one line.
 *
 * Internal on purpose: [BossLogger] and [LogSanitizer] are also shipped in the plugin api jar, and a
 * new public member here would exist for the host and not for a plugin compiled against that jar.
 */
internal object LogLineText {
    fun neutralize(text: String): String {
        if (text.codePoints().noneMatch { it == '\\'.code || needsEscaping(it) }) return text
        return buildString(text.length + 16) {
            val codePoints = text.codePoints().iterator()
            while (codePoints.hasNext()) {
                val codePoint = codePoints.nextInt()
                when {
                    codePoint == '\n'.code -> append("\\n")
                    codePoint == '\r'.code -> append("\\r")
                    codePoint == '\\'.code -> append("\\\\")
                    needsEscaping(codePoint) -> Character.toChars(codePoint).forEach { appendEscaped(it) }
                    else -> appendCodePoint(codePoint)
                }
            }
        }
    }

    /**
     * Matches the repo's hidden-character categories (CONTROL, FORMAT, LINE_SEPARATOR, and
     * PARAGRAPH_SEPARATOR) and Unicode whitespace, while keeping ordinary spaces and tabs as legible
     * layout inside one log record. Fast path exits immediately for standard printable ASCII.
     */
    private fun needsEscaping(codePoint: Int): Boolean =
        codePoint != SPACE &&
            codePoint != '\t'.code &&
            (
                codePoint <= SPACE ||
                    (
                        codePoint >= DEL &&
                            (
                                Character.isWhitespace(codePoint) ||
                                    Character.isSpaceChar(codePoint) ||
                                    Character.getType(codePoint) == Character.CONTROL.toInt() ||
                                    Character.getType(codePoint) == Character.FORMAT.toInt()
                            )
                    )
            )

    private fun StringBuilder.appendEscaped(character: Char) {
        append("\\u")
        append(character.code.toString(HEX_RADIX).padStart(HEX_WIDTH, '0'))
    }

    private const val SPACE = 0x20
    private const val DEL = 0x7f
    private const val HEX_RADIX = 16
    private const val HEX_WIDTH = 4
}
