#!/usr/bin/env python3
"""Inline operational SQL for Supabase CLI's isolated test-file mounts.

Run before `supabase test db`. This only generates test files; it never connects
or executes SQL. Generated files are ignored by Git and used on disposable DBs.

`--check` regenerates in memory and compares, without writing. CI runs it after
the generate step so a stale checkout, a hand-edited generated file, or a
template whose operation changed underneath it fails loudly instead of running
the previous content.

Two failure modes this guards, both of which produce a GREEN build that proved
nothing:

  * a generated .sql left behind after its .sql.in was renamed or deleted keeps
    being executed by pg_prove forever, with stale content. Orphans are removed,
    identified by the banner below rather than by a hard-coded list.
  * `supabase test db` invoked without this script silently runs none of these
    suites. Nothing here can detect that from the outside, so the banner records
    provenance and CI keeps generate and check as separate, visible steps.
"""
from pathlib import Path
import re
import sys

BANNER = "-- GENERATED by scripts/test/prepare-db-access-tests.py from {template} - do not edit.\n"

# name -> (operation inlined at each marker, exact number of markers expected)
SUITES = [
    ("master_key_rotation", "ops/rotate_master_encryption_key.sql", 5),
    ("db_access_audit", "audit/identity_disclosure_audit.sql", 4),
    ("client_grant_audit", "audit/client_grant_audit.sql", 2),
]

root = Path(__file__).resolve().parents[2]
tests = root / "supabase/tests"
check_only = "--check" in sys.argv[1:]


def render(name: str, operation: str, count: int) -> tuple[Path, str]:
    template = tests / f"{name}_test.sql.in"
    # r"" keeps the backslash in \ir literal; f"" interpolates the operation.
    marker = rf"\ir ../{operation}"
    source = template.read_text()
    if source.count(marker) != count:
        raise SystemExit(
            f"Expected {count} '{marker}' invocations in {template.name}, found {source.count(marker)}"
        )
    generated = BANNER.format(template=template.name) + source.replace(
        marker, (root / "supabase" / operation).read_text()
    )
    if re.search(r"(?m)^\s*\\(?:ir|i)\b", generated):
        raise SystemExit(f"Unexpanded include in {template.name}")
    return template.with_suffix(""), generated


stale = []
for name, operation, count in SUITES:
    target, generated = render(name, operation, count)
    if check_only:
        if not target.exists() or target.read_text() != generated:
            stale.append(target.name)
    else:
        target.write_text(generated)

# A generated file whose template is gone would keep running with stale content.
# The banner is what identifies one, so a hand-written test is never touched.
expected = {tests / f"{name}_test.sql" for name, _, _ in SUITES}
for existing in sorted(tests.glob("*_test.sql")):
    if existing in expected:
        continue
    if not existing.read_text(errors="ignore").startswith("-- GENERATED by"):
        continue
    if check_only:
        stale.append(f"{existing.name} (orphan)")
    else:
        existing.unlink()
        print(f"removed orphaned generated suite: {existing.name}")

if check_only and stale:
    raise SystemExit(
        "Generated DB test files are stale or orphaned: "
        + ", ".join(stale)
        + "\nRun scripts/test/prepare-db-access-tests.py and retry."
    )
