import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
test('application isolation, admission replay, role, lease, media and CAS',async()=>{const db=new PGlite({extensions:{pgcrypto}});try{
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE SCHEMA auth; CREATE SCHEMA extensions; CREATE EXTENSION pgcrypto WITH SCHEMA extensions; CREATE TABLE auth.users(id uuid PRIMARY KEY); CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.role',true),'') $$; GRANT USAGE ON SCHEMA auth TO authenticated,anon,service_role;`);
await db.exec(await readFile(new URL('../../migrations/20260928000000_application_sharing.sql',import.meta.url),'utf8'));
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',session_id='33333333-3333-4333-8333-333333333333',generation='44444444-4444-4444-8444-444444444444',device_id='55555555-5555-4555-8555-555555555555';
await db.query('INSERT INTO auth.users VALUES($1),($2)',[a,b]);
const as=async(actor,role='authenticated')=>{await db.exec('RESET ROLE; SET ROLE '+role);await db.query("SELECT set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role',$2,false)",[actor,role]);};
const scalar=async(sql,args=[]) => (await db.query(sql,args)).rows[0].value;
let activeGeneration=generation;
const call=(action,args={},actor=null)=>scalar('SELECT public.app_sharing_command($1,$2,$3) value',[action,{session_id,generation:activeGeneration,...args},actor]);
const denied=(fn,code='42501')=>assert.rejects(fn,e=>e.code===code);
await as(a);await assert.rejects(db.query('SELECT * FROM public.app_share_sessions'),e=>e.code==='42501');assert.deepEqual(await scalar('SELECT get_user_app_sharing_preferences() value'),{auto_admit:true,auto_control:true,revision:0});
assert.equal((await scalar('SELECT set_user_app_sharing_preferences(false,true,0) value')).revision,1);await denied(()=>scalar('SELECT set_user_app_sharing_preferences(true,true,0) value'),'PT409');await denied(()=>scalar('SELECT get_user_app_sharing_preferences($1) value',[b]));await scalar('SELECT set_user_app_sharing_preferences(true,true,1) value');
const descriptor={device_id,instance_id:device_id,key_epoch:generation,host_public_key:'a'.repeat(59),name:'Synthetic',windows:[{id:'window-1',title:'Window'}],viewer_url:'https://viewer.example/#k='+'a'.repeat(43)};
const registered=await call('register',descriptor);assert.ok(registered.host_peer_id);await denied(()=>call('register',descriptor),'PT409');assert.equal((await call('list')).sessions.length,1);assert.equal((await call('list')).sessions[0].host_peer_id,undefined);
await as(b);assert.equal((await call('list')).sessions.length,0);for(const action of ['heartbeat','stop','admit'])await denied(()=>call(action,{device_id,role:'view'}));await denied(()=>call('register',descriptor));await as(a);
const ticket=await call('admit',{device_id,role:'view'});await denied(()=>call('consume',{device_id,role:'control',ticket:ticket.ticket}));await denied(()=>call('consume',{device_id:b,role:'view',ticket:ticket.ticket}));const view=await call('consume',{device_id,role:'view',ticket:ticket.ticket});await denied(()=>call('consume',{device_id,role:'view',ticket:ticket.ticket}));await denied(()=>call('controlAcquire',{peer_id:view.peer_id}));await denied(()=>call('_mediaGet',{peer_id:view.peer_id,window_id:'window-1'}));
const admit=async()=>{const t=await call('admit',{device_id,role:'control'});return call('consume',{device_id,role:'control',ticket:t.ticket});};const controller=await admit(),other=await admit();const lease=await call('controlAcquire',{peer_id:controller.peer_id});assert.ok(lease.control_secret);assert.equal((await call('controlRenew',{peer_id:controller.peer_id,lease_id:lease.lease_id})).lease_id,lease.lease_id);await denied(()=>call('controlRenew',{peer_id:other.peer_id,lease_id:lease.lease_id}));await denied(()=>call('controlAcquire',{peer_id:other.peer_id}),'PT409');await denied(()=>call('controlPoll',{peer_id:controller.peer_id}));assert.equal((await call('controlPoll',{host_peer_id:registered.host_peer_id})).lease.lease_id,lease.lease_id);
await denied(()=>call('mediaDemand',{peer_id:view.peer_id}));assert.deepEqual((await call('mediaDemand',{host_peer_id:registered.host_peer_id})).windows,[{window_id:'window-1',viewers:0}]);
await as(a,'service_role');const media={peer_id:controller.peer_id,window_id:'window-1'},operation='66666666-6666-4666-8666-666666666666';await call('_mediaLock',{...media,operation},a);await denied(()=>call('_mediaLock',{...media,operation},a),'PT409');await call('_mediaBind',{...media,sfu_id:'sfu-fixture'},a);assert.equal((await call('_mediaGet',media,a)).publisher,false);await denied(()=>call('_mediaGet',{...media,window_id:'unshared'},a));await call('_controlAuthorize',{...media,lease_id:lease.lease_id},a);await call('_mediaUnlock',{...media,operation},a);assert.deepEqual((await call('mediaDemand',{host_peer_id:registered.host_peer_id},a)).windows,[{window_id:'window-1',viewers:1}]);
await as(a);assert.equal((await call('controlRelease',{host_peer_id:registered.host_peer_id})).released,true);await as(a,'service_role');await denied(()=>call('_controlAuthorize',{...media,lease_id:lease.lease_id},a));await as(a,'service_role');
await call('_mediaTrack',{...media,mid:'0'},a);
await as(a);await call('revoke',{host_peer_id:registered.host_peer_id,target_peer_id:controller.peer_id});
await denied(()=>call('peerHeartbeat',{peer_id:controller.peer_id}));
await as(a,'service_role');
const cleanup=await call('_cleanupList',{},a);assert.equal(cleanup.length,1);assert.equal(cleanup[0].descriptor.sfu_id,'sfu-fixture');
await call('_cleanupAck',{cleanup_id:cleanup[0].id},a);assert.equal((await call('_cleanupList',{},a)).length,0);
await as(a);activeGeneration='88888888-8888-4888-8888-888888888888';await call('register',{...descriptor,key_epoch:activeGeneration});const expired=await call('admit',{device_id,role:'view'});
await db.exec('RESET ROLE');await db.query('UPDATE public.app_share_tickets SET expires_at=now()-interval \'1 second\'');await as(a);
await denied(()=>call('consume',{ticket:expired.ticket,device_id,role:'view'}));
const old=await call('admit',{device_id,role:'view'}),next='77777777-7777-4777-8777-777777777777';await call('register',{...descriptor,generation:next,key_epoch:next});await denied(()=>call('consume',{ticket:old.ticket,role:'view',device_id}));await denied(()=>call('heartbeat'));activeGeneration=next;await scalar('SELECT set_user_app_sharing_preferences(false,false,2) value');await denied(()=>call('heartbeat'));assert.equal((await call('list')).sessions.length,0);await scalar('SELECT set_user_app_sharing_preferences(true,true,3) value');activeGeneration='99999999-9999-4999-8999-999999999999';await call('register',{...descriptor,key_epoch:activeGeneration});await call('stop');await denied(()=>call('heartbeat',{generation:next}));
const healthHost=await call('register',{...descriptor});
const cleanPeer=await admit();await as(a,'service_role');
await call('_mediaBind',{peer_id:cleanPeer.peer_id,window_id:'window-1',sfu_id:'normal-close'},a);
await call('_mediaTrack',{peer_id:cleanPeer.peer_id,window_id:'window-1',mid:'0'},a);
await call('_mediaDelete',{peer_id:cleanPeer.peer_id,window_id:'window-1'},a);
assert.equal((await call('_cleanupList',{},a)).length,0);
await as(a);await denied(()=>call('peerHeartbeat',{peer_id:cleanPeer.peer_id}));assert.ok((await call('heartbeat')).expires_at);
const expiring=await admit();await as(a,'service_role');
await call('_mediaBind',{peer_id:expiring.peer_id,window_id:'window-1',sfu_id:'expired-viewer'},a);
await call('_mediaTrack',{peer_id:expiring.peer_id,window_id:'window-1',mid:'0'},a);
await db.exec('RESET ROLE');await db.query("UPDATE public.app_share_peers SET expires_at=now()-interval '1 second' WHERE id=$1",[expiring.peer_id]);
await as(a);assert.equal((await call('mediaDemand',{host_peer_id:healthHost.host_peer_id})).generation_revoked,true);await denied(()=>call('heartbeat'));assert.equal((await call('list')).sessions.length,0);
await as(a,'service_role');
const nonce='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', timestamp=Math.floor(Date.now()/1000);
const jobs=await scalar('SELECT claim_app_sharing_cleanup($1,$2) value',[nonce,timestamp]);assert.equal(jobs.jobs.length,1);
await denied(()=>scalar('SELECT claim_app_sharing_cleanup($1,$2) value',[nonce,timestamp]));
const second=await scalar('SELECT claim_app_sharing_cleanup($1,$2) value',['bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',timestamp]);assert.equal(second.jobs.length,0);
assert.equal(await scalar('SELECT ack_app_sharing_cleanup($1,$2) value',[jobs.jobs[0].id,device_id]),false);
assert.equal(await scalar('SELECT ack_app_sharing_cleanup($1,$2) value',[jobs.jobs[0].id,nonce]),true);
await as(a);activeGeneration='cccccccc-cccc-4ccc-8ccc-cccccccccccc';const demandHost=await call('register',{...descriptor,key_epoch:activeGeneration,windows:[{id:'first'},{id:'second'}]});
const demandViewer=await admit();await as(a,'service_role');
await call('_mediaBind',{peer_id:demandViewer.peer_id,window_id:'first',sfu_id:'first-viewer'},a);
assert.deepEqual((await call('mediaDemand',{host_peer_id:demandHost.host_peer_id},a)).windows,[{window_id:'first',viewers:1},{window_id:'second',viewers:0}]);
await call('_mediaBind',{peer_id:demandViewer.peer_id,window_id:'second',sfu_id:'second-viewer'},a);
await call('_mediaDelete',{peer_id:demandViewer.peer_id,window_id:'first'},a);
assert.deepEqual((await call('mediaDemand',{host_peer_id:demandHost.host_peer_id},a)).windows,[{window_id:'first',viewers:0},{window_id:'second',viewers:1}]);
await call('_mediaDelete',{peer_id:demandViewer.peer_id,window_id:'second'},a);
assert.deepEqual((await call('mediaDemand',{host_peer_id:demandHost.host_peer_id},a)).windows,[{window_id:'first',viewers:0},{window_id:'second',viewers:0}]);
await as(a);await call('stop');
await as(a,'anon');await denied(()=>call('list'));

}finally{await db.close();}});
